#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libva-intel-driver
Version  : 1.7.3
Release  : 10
URL      : https://github.com/01org/intel-vaapi-driver/archive/1.7.3.tar.gz
Source0  : https://github.com/01org/intel-vaapi-driver/archive/1.7.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: libva-intel-driver-lib
BuildRequires : libdrm-dev
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libva)
BuildRequires : pkgconfig(libva-drm)
BuildRequires : pkgconfig(libva-wayland)
BuildRequires : pkgconfig(libva-x11)

%description
libva-intel-driver
VA driver for Intel G45 & HD Graphics family
License
-------
Please read the COPYING file available in this package.

%package lib
Summary: lib components for the libva-intel-driver package.
Group: Libraries

%description lib
lib components for the libva-intel-driver package.


%prep
%setup -q -n intel-vaapi-driver-1.7.3

%build
export LANG=C
export SOURCE_DATE_EPOCH=1486063173
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -fno-semantic-interposition "
%autogen --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1486063173
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/dri/i965_drv_video.so
